### ISSUE TITLE
[BUG] Heading of home page cursor

### ISSUE THREAD

**Issue by prajapatdip** [piyushgarg-dev/piyushgargdev-nextjs#43]
**Describe the bug**
When you hover the cursor on the heading "Piyush Garg" of top left corner it should not show pointer otherwise link something to that.

**To Reproduce**
1. Go to Home
2. Hover the cursor on the heading "Piyush Garg" which is on the top left corner

![Screenshot from 2023-06-06 17-19-34](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/104031556/ac82881a-39bc-4a6a-bf2c-1d2149b027ad)

**Comment by TheMohit2003** [comment]
Hey @prajapatdip and @piyushgarg-dev, I believe we can consider implementing one of the two options below:
1) Adding an anchor tag to Piyush Garg, with the home page as the target link.
2) Simply changing the cursor CSS property to `cursor: default;` during hover.

So, @piyushgarg-dev, what option do you think should be implemented? Do you think option 2 is suitable since there is already a `Home` link in the navbar that points to the home page? Alternatively, we can go with option 1, as many websites have icons that by default point to the home page.

**Comment by TheMohit2003** [comment]
This issue has been fixed , thank you for your contribution.

**Comment by prajapatdip** [comment]
This issue hasn't fixed yet!
